### ISSUE TITLE
Time stamp should reflect last reading time

### ISSUE THREAD

**Issue by waynehartman** [opensatx/sawaterlevel-api#1]
One thing I forgot to explain: the time stamp looks like it is generated when the call is made. What this actually refers to is the time at which the level reading was made. Since the measurement is taken every 15 minutes, this time stamp could be up to 15 minutes old.  I don't remember why we decided to include that in this API call, but that's what it means.

We should either remove it from the API, or update the scraper to parse the time at which the reading was taken and recorded by the aquifer authority.

**Comment by davidrleonard** [comment]
Scraper now pares the time the current level data was updated by Edwards Aquifer Authority. 

See PR #2.
