### ISSUE TITLE
10-day Average Incorrect

### ISSUE THREAD

**Issue by waynehartman** [opensatx/sawaterlevel-api#10]
The 10-day average is being reported incorrectly.  As of this writing, the 10-day average is being reported by the service as 636.6, but the Edwards Aquifer site is reporting 637.2.

**Comment by davidrleonard** [comment]
Looking into this.

**Comment by davidrleonard** [comment]
Looks like there were two different numbers being reported (one on http://www.edwardsaquifer.org/, the other on http://www.edwardsaquifer.org/aquifer-data-and-maps/historical-data). Now pulling off the main page.
