### ISSUE TITLE
API not reporting correct average

### ISSUE THREAD

**Issue by waynehartman** [opensatx/sawaterlevel-api#6]
've noticed that the API is continually reporting the average as 635.5, even though, at this moment, it is being reported as 634.4 on the Edwards Aquifer site:

http://www.edwardsaquifer.org/

**Comment by davidrleonard** [comment]
I think I fixed this. It looks like it might've been a problem with floats in Ruby. Looks like it's working now, anyway. Fixed in e57eae88eabcac363dbabf301f4e0d8adff62851.

**Comment by waynehartman** [comment]
Did you deploy the fix to the server?

{
  "level": {
    "recent": 631.89,
    "average": 635.5,
    "lastUpdated": "2014-07-17T09:15:00+00:00"
  },
  "stageLevel": 2.0
}
